services:
  postgres_db_sc:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POST_PASS}
      POSTGRES_USER: ${POST_USER}
      POSTGRES_DB: ${POST_DB}
    ports:
      - "${POST_PORT_EXTERNAL}:${POST_PORT}"
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d
    networks:
      - ecommerceAppNetwork
  pgadmin_sc:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_PASS}
    ports:
      - "${PG_EXTERNAL_PORT}:${PG_INTERNAL_PORT}"
    depends_on:
      - postgres_db_sc
    networks:
      - ecommerceAppNetwork
  ecommerce-spring-boot-app_sc:
    build: .
    depends_on:
      - postgres_db_sc
    ports:
      - "${APP_PORT_EXTERNAL}:${APP_PORT}"
    networks:
      - ecommerceAppNetwork
    env_file:
      - ${ENV_FILE}

networks:
  ecommerceAppNetwork:
    driver: bridge