
#PROFILE
ACTIVE_PROFILE: ${ACTIVE_PROFILE}


#APP_PORT
APP_PORT: ${APP_PORT}
APP_HOST: ${APP_HOST}
APP_SECURE: ${APP_SECURE}

#POSTGRESS
POST_USER: ${POST_USER}
POST_PASS: ${POST_PASS}
POST_DB: ${POST_DB}
POST_PORT: ${POST_PORT}
POST_SERVICE: ${POST_SERVICE}

#EMAIL
MAIL_PORT: ${MAIL_PORT}
MAIL_HOST: ${MAIL_HOST}
MAIL_USERNAME: ${MAIL_USERNAME}
MAIL_PASSWORD: ${MAIL_PASSWORD}
VERIFY_EMAIL_URL: ${VERIFY_EMAIL_URL}


#JWT
JWT_SECRET: ${JWT_SECRET}
JWT_ACCESS_EXP: ${JWT_ACCESS_EXP}
JWT_REFRESH_EXP: ${JWT_REFRESH_EXP}


#admin user
ADMIN_USER: ${ADMIN_USER}
ADMIN_PASSWORD: ${ADMIN_PASSWORD}
ADMIN_ROLES: ${ADMIN_ROLES}

DDL_AUTO: ${DDL_AUTO}


#demo users eg for recruiters
DEMO_USER: ${DEMO_USER}
DEMO_PASSWORD: ${DEMO_PASSWORD}
DEMO_ROLE: ${DEMO_ROLE}

#my cors

WEBSITE_URLS: ${WEBSITE_URLS}

#spring specific
logging:
  level:
    org.springframework.security: DEBUG
